pipeline {
    agent any
    tools {
        go 'go-1.17'
    }

    environment {
        GO111MODULE='on'
    }

    stages {
        stage('Test') {
            steps {
                git 'https://github.com/AdminTurnedDevOps/go-webapp-sample.git' 
                sh 'go test ./...'
            }
        }

        stage('Build and Run') {
            steps {
                git 'https://github.com/AdminTurnedDevOps/go-webapp-sample.git' 
                sh 'go build'
            }
        }

        stage('Run') {
            steps {
                sh 'cd /var/lib/jenkins/workspace/go-full-pipeline && go-webapp-sample &'
        }
    }
}