pipeline {
    agent any
    tools {
        go 'go-1.9'
    }

    environment {
        GO111MODULE='on'
    }

    stages {
        stage('Test') {
            steps {
                git 'https://github.com/AdminTurnedDevOps/go-webapp-sample.git' 
                sh 'go test ./...'
            }
        }
    }
}