pipeline {
    agent any

    stages {
        stage('Dev') {
            steps {
                // Get some code from a Github repository. In reality it would pull from dev branch
                git 'https://github.com/AdminTurnedDevOps/go-webapp-sample.git'
            }
        }

        stage('UAT') {
            steps {
                // Get some code from a Github repository. In reality it would pull from UAT branch
                git 'https://github.com/AdminTurnedDevOps/go-webapp-sample.git'
            }
        }
    }
}